PARTICIPANTS: use this file for creating the remove book from catalog diagram in mastery task 01

@startuml

participant RemoveBookFromCatalogActivity
participant CatalogDao

RemoveBookFromCatalogActivity -> CatalogDao : execute(removeBookFromCatalog)
alt if book does not exist
    CatalogDao --> RemoveBookFromCatalogActivity : BookNotFoundException
else else continue
end
CatalogDao --> RemoveBookFromCatalogActivity : RemoveBookFromCatalogResponse

@enduml